catch {set_db {port:top/a[15]} .original_name {a[15]}}
catch {set_db {port:top/a[14]} .original_name {a[14]}}
catch {set_db {port:top/a[13]} .original_name {a[13]}}
catch {set_db {port:top/a[12]} .original_name {a[12]}}
catch {set_db {port:top/a[11]} .original_name {a[11]}}
catch {set_db {port:top/a[10]} .original_name {a[10]}}
catch {set_db {port:top/a[9]} .original_name {a[9]}}
catch {set_db {port:top/a[8]} .original_name {a[8]}}
catch {set_db {port:top/a[7]} .original_name {a[7]}}
catch {set_db {port:top/a[6]} .original_name {a[6]}}
catch {set_db {port:top/a[5]} .original_name {a[5]}}
catch {set_db {port:top/a[4]} .original_name {a[4]}}
catch {set_db {port:top/a[3]} .original_name {a[3]}}
catch {set_db {port:top/a[2]} .original_name {a[2]}}
catch {set_db {port:top/a[1]} .original_name {a[1]}}
catch {set_db {port:top/a[0]} .original_name {a[0]}}
catch {set_db {port:top/b[15]} .original_name {b[15]}}
catch {set_db {port:top/b[14]} .original_name {b[14]}}
catch {set_db {port:top/b[13]} .original_name {b[13]}}
catch {set_db {port:top/b[12]} .original_name {b[12]}}
catch {set_db {port:top/b[11]} .original_name {b[11]}}
catch {set_db {port:top/b[10]} .original_name {b[10]}}
catch {set_db {port:top/b[9]} .original_name {b[9]}}
catch {set_db {port:top/b[8]} .original_name {b[8]}}
catch {set_db {port:top/b[7]} .original_name {b[7]}}
catch {set_db {port:top/b[6]} .original_name {b[6]}}
catch {set_db {port:top/b[5]} .original_name {b[5]}}
catch {set_db {port:top/b[4]} .original_name {b[4]}}
catch {set_db {port:top/b[3]} .original_name {b[3]}}
catch {set_db {port:top/b[2]} .original_name {b[2]}}
catch {set_db {port:top/b[1]} .original_name {b[1]}}
catch {set_db {port:top/b[0]} .original_name {b[0]}}
catch {set_db {port:top/res[15]} .original_name {res[15]}}
catch {set_db {port:top/res[14]} .original_name {res[14]}}
catch {set_db {port:top/res[13]} .original_name {res[13]}}
catch {set_db {port:top/res[12]} .original_name {res[12]}}
catch {set_db {port:top/res[11]} .original_name {res[11]}}
catch {set_db {port:top/res[10]} .original_name {res[10]}}
catch {set_db {port:top/res[9]} .original_name {res[9]}}
catch {set_db {port:top/res[8]} .original_name {res[8]}}
catch {set_db {port:top/res[7]} .original_name {res[7]}}
catch {set_db {port:top/res[6]} .original_name {res[6]}}
catch {set_db {port:top/res[5]} .original_name {res[5]}}
catch {set_db {port:top/res[4]} .original_name {res[4]}}
catch {set_db {port:top/res[3]} .original_name {res[3]}}
catch {set_db {port:top/res[2]} .original_name {res[2]}}
catch {set_db {port:top/res[1]} .original_name {res[1]}}
catch {set_db {port:top/res[0]} .original_name {res[0]}}
