catch {set_db {port:top/s_mult[47]} .original_name {s_mult[47]}}
catch {set_db {port:top/s_mult[46]} .original_name {s_mult[46]}}
catch {set_db {port:top/s_mult[45]} .original_name {s_mult[45]}}
catch {set_db {port:top/s_mult[44]} .original_name {s_mult[44]}}
catch {set_db {port:top/s_mult[43]} .original_name {s_mult[43]}}
catch {set_db {port:top/s_mult[42]} .original_name {s_mult[42]}}
catch {set_db {port:top/s_mult[41]} .original_name {s_mult[41]}}
catch {set_db {port:top/s_mult[40]} .original_name {s_mult[40]}}
catch {set_db {port:top/s_mult[39]} .original_name {s_mult[39]}}
catch {set_db {port:top/s_mult[38]} .original_name {s_mult[38]}}
catch {set_db {port:top/s_mult[37]} .original_name {s_mult[37]}}
catch {set_db {port:top/s_mult[36]} .original_name {s_mult[36]}}
catch {set_db {port:top/s_mult[35]} .original_name {s_mult[35]}}
catch {set_db {port:top/s_mult[34]} .original_name {s_mult[34]}}
catch {set_db {port:top/s_mult[33]} .original_name {s_mult[33]}}
catch {set_db {port:top/s_mult[32]} .original_name {s_mult[32]}}
catch {set_db {port:top/s_mult[31]} .original_name {s_mult[31]}}
catch {set_db {port:top/s_mult[30]} .original_name {s_mult[30]}}
catch {set_db {port:top/s_mult[29]} .original_name {s_mult[29]}}
catch {set_db {port:top/s_mult[28]} .original_name {s_mult[28]}}
catch {set_db {port:top/s_mult[27]} .original_name {s_mult[27]}}
catch {set_db {port:top/s_mult[26]} .original_name {s_mult[26]}}
catch {set_db {port:top/s_mult[25]} .original_name {s_mult[25]}}
catch {set_db {port:top/s_mult[24]} .original_name {s_mult[24]}}
catch {set_db {port:top/s_mult[23]} .original_name {s_mult[23]}}
catch {set_db {port:top/s_mult[22]} .original_name {s_mult[22]}}
catch {set_db {port:top/s_mult[21]} .original_name {s_mult[21]}}
catch {set_db {port:top/s_mult[20]} .original_name {s_mult[20]}}
catch {set_db {port:top/s_mult[19]} .original_name {s_mult[19]}}
catch {set_db {port:top/s_mult[18]} .original_name {s_mult[18]}}
catch {set_db {port:top/s_mult[17]} .original_name {s_mult[17]}}
catch {set_db {port:top/s_mult[16]} .original_name {s_mult[16]}}
catch {set_db {port:top/s_mult[15]} .original_name {s_mult[15]}}
catch {set_db {port:top/s_mult[14]} .original_name {s_mult[14]}}
catch {set_db {port:top/s_mult[13]} .original_name {s_mult[13]}}
catch {set_db {port:top/s_mult[12]} .original_name {s_mult[12]}}
catch {set_db {port:top/s_mult[11]} .original_name {s_mult[11]}}
catch {set_db {port:top/s_mult[10]} .original_name {s_mult[10]}}
catch {set_db {port:top/s_mult[9]} .original_name {s_mult[9]}}
catch {set_db {port:top/s_mult[8]} .original_name {s_mult[8]}}
catch {set_db {port:top/s_mult[7]} .original_name {s_mult[7]}}
catch {set_db {port:top/s_mult[6]} .original_name {s_mult[6]}}
catch {set_db {port:top/s_mult[5]} .original_name {s_mult[5]}}
catch {set_db {port:top/s_mult[4]} .original_name {s_mult[4]}}
catch {set_db {port:top/s_mult[3]} .original_name {s_mult[3]}}
catch {set_db {port:top/s_mult[2]} .original_name {s_mult[2]}}
catch {set_db {port:top/s_mult[1]} .original_name {s_mult[1]}}
catch {set_db {port:top/s_mult[0]} .original_name {s_mult[0]}}
catch {set_db {port:top/bias[15]} .original_name {bias[15]}}
catch {set_db {port:top/bias[14]} .original_name {bias[14]}}
catch {set_db {port:top/bias[13]} .original_name {bias[13]}}
catch {set_db {port:top/bias[12]} .original_name {bias[12]}}
catch {set_db {port:top/bias[11]} .original_name {bias[11]}}
catch {set_db {port:top/bias[10]} .original_name {bias[10]}}
catch {set_db {port:top/bias[9]} .original_name {bias[9]}}
catch {set_db {port:top/bias[8]} .original_name {bias[8]}}
catch {set_db {port:top/bias[7]} .original_name {bias[7]}}
catch {set_db {port:top/bias[6]} .original_name {bias[6]}}
catch {set_db {port:top/bias[5]} .original_name {bias[5]}}
catch {set_db {port:top/bias[4]} .original_name {bias[4]}}
catch {set_db {port:top/bias[3]} .original_name {bias[3]}}
catch {set_db {port:top/bias[2]} .original_name {bias[2]}}
catch {set_db {port:top/bias[1]} .original_name {bias[1]}}
catch {set_db {port:top/bias[0]} .original_name {bias[0]}}
catch {set_db {port:top/y[17]} .original_name {y[17]}}
catch {set_db {port:top/y[16]} .original_name {y[16]}}
catch {set_db {port:top/y[15]} .original_name {y[15]}}
catch {set_db {port:top/y[14]} .original_name {y[14]}}
catch {set_db {port:top/y[13]} .original_name {y[13]}}
catch {set_db {port:top/y[12]} .original_name {y[12]}}
catch {set_db {port:top/y[11]} .original_name {y[11]}}
catch {set_db {port:top/y[10]} .original_name {y[10]}}
catch {set_db {port:top/y[9]} .original_name {y[9]}}
catch {set_db {port:top/y[8]} .original_name {y[8]}}
catch {set_db {port:top/y[7]} .original_name {y[7]}}
catch {set_db {port:top/y[6]} .original_name {y[6]}}
catch {set_db {port:top/y[5]} .original_name {y[5]}}
catch {set_db {port:top/y[4]} .original_name {y[4]}}
catch {set_db {port:top/y[3]} .original_name {y[3]}}
catch {set_db {port:top/y[2]} .original_name {y[2]}}
catch {set_db {port:top/y[1]} .original_name {y[1]}}
catch {set_db {port:top/y[0]} .original_name {y[0]}}
