catch {set_db {port:top/X[7]} .original_name {X[7]}}
catch {set_db {port:top/X[6]} .original_name {X[6]}}
catch {set_db {port:top/X[5]} .original_name {X[5]}}
catch {set_db {port:top/X[4]} .original_name {X[4]}}
catch {set_db {port:top/X[3]} .original_name {X[3]}}
catch {set_db {port:top/X[2]} .original_name {X[2]}}
catch {set_db {port:top/X[1]} .original_name {X[1]}}
catch {set_db {port:top/X[0]} .original_name {X[0]}}
catch {set_db {port:top/y[15]} .original_name {y[15]}}
catch {set_db {port:top/y[14]} .original_name {y[14]}}
catch {set_db {port:top/y[13]} .original_name {y[13]}}
catch {set_db {port:top/y[12]} .original_name {y[12]}}
catch {set_db {port:top/y[11]} .original_name {y[11]}}
catch {set_db {port:top/y[10]} .original_name {y[10]}}
catch {set_db {port:top/y[9]} .original_name {y[9]}}
catch {set_db {port:top/y[8]} .original_name {y[8]}}
catch {set_db {port:top/y[7]} .original_name {y[7]}}
catch {set_db {port:top/y[6]} .original_name {y[6]}}
catch {set_db {port:top/y[5]} .original_name {y[5]}}
catch {set_db {port:top/y[4]} .original_name {y[4]}}
catch {set_db {port:top/y[3]} .original_name {y[3]}}
catch {set_db {port:top/y[2]} .original_name {y[2]}}
catch {set_db {port:top/y[1]} .original_name {y[1]}}
catch {set_db {port:top/y[0]} .original_name {y[0]}}
